DATASET:
  training_set_name: livecell
  test_set_name: null
  image_root: ../data

MODEL:
  model_zoo_path: Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml
  pretrained_model_path: Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml
  eval_model_path: null
