DATASET:
  training_set_name: livecell
  test_set_name: null
  image_root: ../data

MODEL:
  model_zoo_path: ../venv/lib/python3.8/site-packages/centermask2/configs/centermask/centermask_V_99_eSE_dcn_FPN_ms_3x.yaml
  pretrained_model_path: ../venv/lib/python3.8/site-packages/centermask2/configs/centermask/centermask_V_99_eSE_dcn_FPN_ms_3x.yaml
