model_name: segresnet
model_path: ../models/segresnet

model:
  init_filters: 8
  dropout_prob: null
  blocks_down:
    - 1
    - 2
    - 2
    - 4
  blocks_up:
    - 1
    - 1
    - 1

training:
  loss: DiceLoss
  loss_parameters:
    smooth_nr: 0
    smooth_dr: 1e-5
    squared_pred: True
    sigmoid: True
  optimizer: Adam
  optimizer_parameters:
    lr: 0.001
    betas:
      - 0.9
      - 0.999
    weight_decay: 0
  lr_scheduler: CosineAnnealingLR
  lr_scheduler_parameters:
    T_max: 50
    eta_min: 0.00001
    last_epoch: -1
  data_loader:
    batch_size: 2
    num_workers: 0
  epochs: 100
  early_stopping_patience: 10
  deterministic_cudnn: False
  random_state: 42
