DATASET:
  training_set_name: livecell
  test_set_name: null
  image_root: ../data

MODEL:
  model_zoo_path: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml
  pretrained_model_path: COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml
